FROM public.ecr.aws/glue/aws-glue-libs:5

WORKDIR /home/spark/shared/pyspark

COPY requirements_pyspark.txt .

RUN pip install --no-cache-dir -r requirements_pyspark.txt

COPY src ./src

COPY data ./data

CMD ["spark-submit", "src/transformer.py"]