FROM python:3.11-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    build-essential \
    fonts-noto-cjk \
    && rm -rf /var/lib/apt/lists/*

# Pythonライブラリをインストール
COPY requirements/requirements_dev.txt .

RUN pip install --no-cache-dir -r requirements_dev.txt

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]